page_categories:
  - name: Economy
    id: economy
  - name: Politics and Laws
    id: politics-and-laws
  - name: Society
    id: society
  - name: Sports
    id: sports
  - name: Tech
    id: tech
  - name: Health
    id: health
